"""tripll.parse — input parsers that build a :class:`~tripll.graph.RunGraph`.

Two modes:

* **Mode A** (:mod:`tripll.parse.parallel_wave`) — parse an existing
  ``parallel-wave.md`` set into a ``RunGraph``.
* **Mode B** (:mod:`tripll.parse.plan_files`) — parse a folder of plain
  wave-plan files, generate a ``parallel-wave.md`` manifest, then run Mode A.

Exports:
    build_graph_from_dir — auto-detect the mode for an input directory and
        return the derived ``RunGraph``.
    detect_mode — classify an input directory as Mode ``'A'`` or ``'B'``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Literal

from tripll.parse.parallel_wave import build_run_graph_from_dir
from tripll.parse.plan_files import build_graph_mode_b

if TYPE_CHECKING:
    from pathlib import Path

    from tripll.graph import RunGraph

__all__ = ["build_graph_from_dir", "detect_mode"]


def detect_mode(input_dir: Path) -> Literal["A", "B"]:
    """Classify *input_dir* as Mode A or Mode B.

    Mode A when a hand-written ``parallel-wave.md`` is present. Mode B when
    only plain ``*-wave-plan.md`` files exist, or when ``parallel-wave.md`` was
    generated by :mod:`tripll.parse.plan_files` (regenerate from wave files).

    Args:
        input_dir (Path): The input directory to classify.

    Returns:
        Literal["A", "B"]: ``'A'`` for a curated parallel-wave set, else ``'B'``.

    Examples:
        >>> import tempfile
        >>> from pathlib import Path
        >>> with tempfile.TemporaryDirectory() as d:
        ...     detect_mode(Path(d))
        'B'
    """
    pw = input_dir / "parallel-wave.md"
    if pw.exists():
        head = pw.read_text()[:400]
        if "Generated by:" in head and (
            "tripll.parse.plan_files" in head or "tripll.parse.manifest" in head
        ):
            return "B"
        if head.startswith("# parallel-wave manifest (tripll v1)"):
            return "B"
        return "A"
    return "B"


def build_graph_from_dir(input_dir: Path, *, run_id: str) -> RunGraph:
    """Build a ``RunGraph`` from *input_dir*, auto-detecting the parse mode.

    Args:
        input_dir (Path): Directory containing either a ``parallel-wave.md``
            set (Mode A) or plain wave-plan files (Mode B).
        run_id (str): Run identifier to embed in the graph.

    Returns:
        RunGraph: The derived run graph.

    Raises:
        FileNotFoundError: If *input_dir* does not exist.

    Examples:
        >>> # See tests/test_parse_mode_a.py for a full round-trip example.
        >>> callable(build_graph_from_dir)
        True
    """
    if not input_dir.exists():
        raise FileNotFoundError(f"Input directory not found: {input_dir}")
    from tripll.parse.wave_plan_v1 import build_graph_from_v1_dir, parse_wave_plan_v1

    wave_files = sorted(input_dir.glob("*-wave-plan.md"))
    if wave_files and any(parse_wave_plan_v1(f).has_execution_graph for f in wave_files):
        return build_graph_from_v1_dir(input_dir, run_id=run_id)
    if detect_mode(input_dir) == "A":
        return build_run_graph_from_dir(input_dir, run_id=run_id)
    return build_graph_mode_b(input_dir, run_id=run_id)
