"""tripll.parse.manifest — deterministic ``parallel-wave.md`` generation.

Writes a stable, sorted manifest from a :class:`~tripll.graph.RunGraph` (no
timestamps; same input → same bytes).

Exports:
    write_parallel_wave_manifest — write ``parallel-wave.md`` to disk.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

    from tripll.graph import RunGraph


def write_parallel_wave_manifest(graph: RunGraph, output_path: Path) -> str:
    """Write a deterministic ``parallel-wave.md`` for *graph*.

    Args:
        graph (RunGraph): Parsed run graph.
        output_path (Path): Destination file path.

    Returns:
        str: Manifest text written (for tests).
    """
    lines: list[str] = [
        "# parallel-wave manifest (tripll v1)\n",
        "\n",
        "**Generated by:** tripll.parse.manifest (deterministic)\n",
        f"**Source mode:** {graph.source_mode}\n",
        f"**Run-id seed:** {graph.run_id}\n",
        "\n---\n\n",
        "## Plan index\n\n",
        "| # | Plan | Effort | Lane |\n",
        "|---|------|--------|------|\n",
    ]
    plan_rows: list[tuple[int, str, str, str, str]] = []
    for lane_id in sorted(graph.lanes):
        lane = graph.lanes[lane_id]
        for node in sorted(lane.waves, key=lambda n: n.wave_id):
            plan_rows.append(
                (
                    len(plan_rows) + 1,
                    node.plan_id,
                    node.wave_id,
                    node.effort,
                    lane_id,
                )
            )
    for num, plan_id, wave_id, effort, lane_id in plan_rows:
        lines.append(f"| {num} | {plan_id} | {effort} | {lane_id} | {wave_id} |\n")

    lines.extend(["\n---\n\n", "## Phase diagram\n\n", "```\n"])
    for batch in graph.batches:
        waves = ", ".join(batch.wave_ids) if batch.wave_ids else ", ".join(batch.lanes)
        gate = " [HUMAN GATE]" if batch.is_human_gate else ""
        lines.append(f"Phase {batch.batch_id} — {batch.label}{gate}")
        if waves:
            lines.append(f" ({waves})")
        lines.append("\n")
    lines.append("```\n\n---\n\n")

    lines.extend(
        [
            "## Batch table\n\n",
            "| batch_id | waves | lanes | human_gate |\n",
            "|----------|-------|-------|------------|\n",
        ]
    )
    for batch in graph.batches:
        w = ", ".join(sorted(batch.wave_ids))
        ln = ", ".join(sorted(batch.lanes))
        hg = "yes" if batch.is_human_gate else ""
        lines.append(f"| {batch.batch_id} | {w} | {ln} | {hg} |\n")

    lines.extend(["\n---\n\n", "## Pre-0 gates\n\n"])
    for i, gate in enumerate(graph.pre0_gates, 1):
        lines.append(f"{i}. {gate}\n")
    if not graph.pre0_gates:
        lines.append("(none)\n")

    text = "".join(lines)
    output_path.write_text(text)
    return text
